In [22]:
import numpy as np

In [23]:
a = np.random.random(5)

In [24]:
expa = np.exp(a)

In [25]:
print(a)
print(expa)

[0.25080124 0.93037317 0.45289409 0.53235514 0.90653363]
[1.28505464 2.53545516 1.57285759 1.70293824 2.47572585]


In [26]:
answer = expa / expa.sum()

In [27]:
print(answer)

[0.13425098 0.26488161 0.16431805 0.17790771 0.25864163]


In [28]:
answer.sum()

1.0

In [29]:
A = np.random.random((100, 5))

In [30]:
expA = np.exp(A)

In [31]:
answerA = expA / expA.sum(axis=1, keepdims=True)

In [32]:
answerA.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
answerA.shape

(100, 5)